FROM golang:1.22-alpine

# Install protoc and git
RUN apk add --no-cache git protobuf

# Install protoc-gen-go
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

# Set PATH for protoc-gen-go
ENV PATH="/go/bin:$PATH"

WORKDIR /app
COPY . .

# Generate protobuf files
RUN protoc --go_out=. --go_opt=paths=source_relative  proto/payload.proto 

# Build binary
RUN go build -o app ./cmd/main.go

EXPOSE 8080
CMD ["./app"]
