# Map of sensitive JSON paths to redact or hash in murmapp.hook
# Applied to every incoming update.message

privacy_keys:
  # Original sender of the message
  - message.from.id
  - message.from.first_name
  - message.from.last_name
  - message.from.username

  # Chat where the message is sent (in private chats same as from)
  - message.chat.id
  - message.chat.first_name
  - message.chat.last_name
  - message.chat.username

  # Reply target message
  - message.reply_to_message.from.id
  - message.reply_to_message.from.first_name
  - message.reply_to_message.from.last_name
  - message.reply_to_message.from.username

  - message.reply_to_message.chat.id
  - message.reply_to_message.chat.first_name
  - message.reply_to_message.chat.last_name
  - message.reply_to_message.chat.username

  # Forwarded messages from user origin
  - message.forward_from.id
  - message.forward_from.first_name
  - message.forward_from.last_name
  - message.forward_from.username

  - message.forward_origin.sender_user.id
  - message.forward_origin.sender_user.first_name
  - message.forward_origin.sender_user.last_name
  - message.forward_origin.sender_user.username

# Exceptions:
# - message.forward_from_chat and message.forward_origin.chat with type == "channel"
#   are considered public and are not redacted
