// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/encrypted_telegram_id.proto

package hookpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptedTelegramID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramXid   string                 `protobuf:"bytes,1,opt,name=telegram_xid,json=telegramXid,proto3" json:"telegram_xid,omitempty"`
	EncryptedId   []byte                 `protobuf:"bytes,2,opt,name=encrypted_id,json=encryptedId,proto3" json:"encrypted_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedTelegramID) Reset() {
	*x = EncryptedTelegramID{}
	mi := &file_proto_encrypted_telegram_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedTelegramID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedTelegramID) ProtoMessage() {}

func (x *EncryptedTelegramID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encrypted_telegram_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedTelegramID.ProtoReflect.Descriptor instead.
func (*EncryptedTelegramID) Descriptor() ([]byte, []int) {
	return file_proto_encrypted_telegram_id_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptedTelegramID) GetTelegramXid() string {
	if x != nil {
		return x.TelegramXid
	}
	return ""
}

func (x *EncryptedTelegramID) GetEncryptedId() []byte {
	if x != nil {
		return x.EncryptedId
	}
	return nil
}

var File_proto_encrypted_telegram_id_proto protoreflect.FileDescriptor

const file_proto_encrypted_telegram_id_proto_rawDesc = "" +
	"\n" +
	"!proto/encrypted_telegram_id.proto\x12\x04hook\"[\n" +
	"\x13EncryptedTelegramID\x12!\n" +
	"\ftelegram_xid\x18\x01 \x01(\tR\vtelegramXid\x12!\n" +
	"\fencrypted_id\x18\x02 \x01(\fR\vencryptedIdB\x1bZ\x19murmapp.hook/proto;hookpbb\x06proto3"

var (
	file_proto_encrypted_telegram_id_proto_rawDescOnce sync.Once
	file_proto_encrypted_telegram_id_proto_rawDescData []byte
)

func file_proto_encrypted_telegram_id_proto_rawDescGZIP() []byte {
	file_proto_encrypted_telegram_id_proto_rawDescOnce.Do(func() {
		file_proto_encrypted_telegram_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_encrypted_telegram_id_proto_rawDesc), len(file_proto_encrypted_telegram_id_proto_rawDesc)))
	})
	return file_proto_encrypted_telegram_id_proto_rawDescData
}

var file_proto_encrypted_telegram_id_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_encrypted_telegram_id_proto_goTypes = []any{
	(*EncryptedTelegramID)(nil), // 0: hook.EncryptedTelegramID
}
var file_proto_encrypted_telegram_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_encrypted_telegram_id_proto_init() }
func file_proto_encrypted_telegram_id_proto_init() {
	if File_proto_encrypted_telegram_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_encrypted_telegram_id_proto_rawDesc), len(file_proto_encrypted_telegram_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_encrypted_telegram_id_proto_goTypes,
		DependencyIndexes: file_proto_encrypted_telegram_id_proto_depIdxs,
		MessageInfos:      file_proto_encrypted_telegram_id_proto_msgTypes,
	}.Build()
	File_proto_encrypted_telegram_id_proto = out.File
	file_proto_encrypted_telegram_id_proto_goTypes = nil
	file_proto_encrypted_telegram_id_proto_depIdxs = nil
}
