# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/payload.proto

require 'google/protobuf'


descriptor_data = "\n\x13proto/payload.proto\x12\x04hook\"X\n\x16TelegramWebhookPayload\x12\x12\n\nwebhook_id\x18\x01 \x01(\t\x12\x10\n\x08raw_body\x18\x02 \x01(\x0c\x12\x18\n\x10received_at_unix\x18\x03 \x01(\x03\x42\x1bZ\x19murmapp.hook/proto;hookpbb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Hook
  TelegramWebhookPayload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hook.TelegramWebhookPayload").msgclass
end
