// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/payload.proto

package hookpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelegramWebhookPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WebhookId        string                 `protobuf:"bytes,1,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	EncryptedPayload []byte                 `protobuf:"bytes,2,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	ReceivedAtUnix   int64                  `protobuf:"varint,3,opt,name=received_at_unix,json=receivedAtUnix,proto3" json:"received_at_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TelegramWebhookPayload) Reset() {
	*x = TelegramWebhookPayload{}
	mi := &file_proto_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramWebhookPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramWebhookPayload) ProtoMessage() {}

func (x *TelegramWebhookPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramWebhookPayload.ProtoReflect.Descriptor instead.
func (*TelegramWebhookPayload) Descriptor() ([]byte, []int) {
	return file_proto_payload_proto_rawDescGZIP(), []int{0}
}

func (x *TelegramWebhookPayload) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *TelegramWebhookPayload) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *TelegramWebhookPayload) GetReceivedAtUnix() int64 {
	if x != nil {
		return x.ReceivedAtUnix
	}
	return 0
}

var File_proto_payload_proto protoreflect.FileDescriptor

const file_proto_payload_proto_rawDesc = "" +
	"\n" +
	"\x13proto/payload.proto\x12\x04hook\"\x8e\x01\n" +
	"\x16TelegramWebhookPayload\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x01 \x01(\tR\twebhookId\x12+\n" +
	"\x11encrypted_payload\x18\x02 \x01(\fR\x10encryptedPayload\x12(\n" +
	"\x10received_at_unix\x18\x03 \x01(\x03R\x0ereceivedAtUnixB\x1bZ\x19murmapp.hook/proto;hookpbb\x06proto3"

var (
	file_proto_payload_proto_rawDescOnce sync.Once
	file_proto_payload_proto_rawDescData []byte
)

func file_proto_payload_proto_rawDescGZIP() []byte {
	file_proto_payload_proto_rawDescOnce.Do(func() {
		file_proto_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payload_proto_rawDesc), len(file_proto_payload_proto_rawDesc)))
	})
	return file_proto_payload_proto_rawDescData
}

var file_proto_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_payload_proto_goTypes = []any{
	(*TelegramWebhookPayload)(nil), // 0: hook.TelegramWebhookPayload
}
var file_proto_payload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_payload_proto_init() }
func file_proto_payload_proto_init() {
	if File_proto_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payload_proto_rawDesc), len(file_proto_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_payload_proto_goTypes,
		DependencyIndexes: file_proto_payload_proto_depIdxs,
		MessageInfos:      file_proto_payload_proto_msgTypes,
	}.Build()
	File_proto_payload_proto = out.File
	file_proto_payload_proto_goTypes = nil
	file_proto_payload_proto_depIdxs = nil
}
