# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/registration.proto

require 'google/protobuf'


descriptor_data = "\n\x18proto/registration.proto\x12\x04hook\"=\n\x16RegisterWebhookRequest\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61pi_key_bot\x18\x02 \x01(\t\"=\n\x17RegisterWebhookResponse\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\x12\n\nwebhook_id\x18\x02 \x01(\tB\x1bZ\x19murmapp.hook/proto;hookpbb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Hook
  RegisterWebhookRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hook.RegisterWebhookRequest").msgclass
  RegisterWebhookResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hook.RegisterWebhookResponse").msgclass
end
