name: Deploy murmurapp.hook

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SECRET_SALT: ${{ secrets.SECRET_SALT }}
      TELEGRAM_ID_ENCRYPTION_KEY: ${{ secrets.TELEGRAM_ID_ENCRYPTION_KEY }}
      RABBITMQ_URL: ${{ secrets.RABBITMQ_URL }}
      WEB_HOOK_HOST: ${{ secrets.WEB_HOOK_HOST }}
      APP_PORT: ${{ secrets.APP_PORT }}
      DEBUG: ${{ secrets.DEBUG }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build binary
        run: go build -o app ./cmd/main.go

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          source: "app"
          target: "~/murmapp/murmapp.hook"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          envs: SECRET_SALT,RABBITMQ_URL,WEB_HOOK_HOST,APP_PORT,DEBUG,TELEGRAM_ID_ENCRYPTION_KEY
          script: |
            cd ~/murmapp/murmapp.hook

            cat <<EOF > .env
            SECRET_SALT=$SECRET_SALT
            TELEGRAM_ID_ENCRYPTION_KEY=$TELEGRAM_ID_ENCRYPTION_KEY
            RABBITMQ_URL=$RABBITMQ_URL
            WEB_HOOK_HOST=$WEB_HOOK_HOST
            APP_PORT=$APP_PORT
            DEBUG=$DEBUG
            EOF

            sudo systemctl restart murmapp-hook.service
